### PR TITLE
Fix instructions

### PR DESCRIPTION
**Pull request by kpedro88**
The pypi package name was written incorrectly. Also fixed a typo.

Updated to fix some issues with how the config file is described.

### CODE REVIEW

**Review by AleksCipri — APPROVED** [review]

**Comment by kpedro88** [comment]
Tried to fix some more issues that came up. Things I can't fix myself:
* version on pypi is out of date with respect to what's on github
* some dependencies are not declared. so far, I've found `easydict`, `torchvision`, and `apex` (the Nvidia package, not the one on pypi). it also seems like the code isn't compatible w/ pytorch 2.0+, which should be declared. maybe this is only designed to run on colab? if so, should be stated explicitly.
* these imports/classes don't seem to exist anywhere: https://github.com/deepskies/DeepAstroUDA/blob/69340fe84d13a37cb5818d462344573b7f9297d1/deep_astro_uda/model/get_loader.py#L1-L2

**Comment by kpedro88** [comment]
(personally, I'm not sure what advantage is gained from using cleo over simple argparse...)

**Comment by kpedro88** [comment]
Removed binary files that should not be tracked (they were probably added because there was no gitignore). Artifacts should be attached to GitHub release pages.

**Comment by kpedro88** [comment]
Another issue: `entropy_margin` (defined [here](https://github.com/VisionLearningGroup/DANCE/blob/6d84da24961aca75b011ed5fe185f36c4a3c1b88/utils/loss.py#L8) in the DANCE repo) seems to be omitted from [loss.py](https://github.com/deepskies/DeepAstroUDA/blob/main/deep_astro_uda/model/loss.py) in this repo and isn't defined anywhere else in the repo.

Similarly, the base model definitions aren't found in this repo, and seem to come from DANCE: https://github.com/VisionLearningGroup/DANCE/blob/main/models/basenet.py

Is this code base supposed to be built on top of DANCE or something? I don't see that in the installation scripts or instructions.

**Pull request merged**
